### ISSUE TITLE
Lab is passed in vsc but not in Codegrade due to pytest test collection failure

### ISSUE THREAD

**Issue by Jiyu13** [learn-co-curriculum/python-p4-building-get-api-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6259/assignments/233440?module_item_id=547398

### Concern

server.testing.models_test
collection failure
../.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1900: in _execute_context
    self.dialect.do_execute(
../.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py:736: in do_execute
    cursor.execute(statement, parameters)
E   sqlite3.OperationalError: no such table: bakeries

The above exception was the direct cause of the following exception:
server/testing/models_test.py:6: in <module>
    class TestBakery:
server/testing/models_test.py:11: in TestBakery
    for mb in b:
../.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2900: in __iter__
    return self._iter().__iter__()
../.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2907: in _iter
    result = self.session.execute(
../.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py:1712: in execute
    result = conn._execute_20(statement, params or {}, execution_options)
../.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1705: in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
../.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:333: in _execute_on_connection
    return connection._execute_clauseelement(
../.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1572: in _execute_clauseelement
    ret = self._execute_context(
../.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1943: in _execute_context
    self._handle_dbapi_exception(
../.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2124: in _handle_dbapi_exception
    util.raise_(
../.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208: in raise_
    raise exception
../.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1900: in _execute_context
    self.dialect.do_execute(
../.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py:736: in do_execute
    cursor.execute(statement, parameters)
E   sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: bakeries
E   [SQL: SELECT bakeries.id AS bakeries_id, bakeries.name AS bakeries_name, bakeries.created_at AS bakeries_created_at, bakeries.updated_at AS bakeries_updated_at 
E   FROM bakeries 
E   WHERE bakeries.name = ?]
E   [parameters: ('Mr. Bakery',)]
E   (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by professor-ben** [comment]
Can you share your `.gitignore` from the root directory? You may be working with an old (i.e. 24-hour old) version.

**Comment by Jiyu13** [comment]
Here it is:
https://github.com/Jiyu13/python-p4-building-get-api-lab/blob/main/.gitignore

**Comment by professor-ben** [comment]
That's odd. It looks like a migration hasn't been run. Can you make sure that the database you're pushing up has all of the tables it needs to (especially `bakeries`)?

**Comment by Jiyu13** [comment]
https://github.com/Jiyu13/python-p4-building-get-api-lab/blob/main/server/migrations/versions/11449af16b0d_create_tables_bakeries_baked_goods.py

I think  `bakeries` is in the migration file. I had other labs with the same issue, so I'm not sure if it's just happening to me.

**Comment by professor-ben** [comment]
Can you run `tree` from the repo root and paste it here? You might have two databases.

**Comment by Jiyu13** [comment]
```
.
├── CONTRIBUTING.md
├── LICENSE.md
├── Pipfile
├── Pipfile.lock
├── README.md
├── pytest.ini
└── server
    ├── __pycache__
    │   └── models.cpython-38.pyc
    ├── app.py
    ├── debug.py
    ├── instance
    │   └── app.db
    ├── migrations
    │   ├── README
    │   ├── alembic.ini
    │   ├── env.py
    │   ├── script.py.mako
    │   └── versions
    │       └── 11449af16b0d_create_tables_bakeries_baked_goods.py
    ├── models.py
    ├── seed.py
    └── testing
        ├── app_test.py
        ├── conftest.py
        └── models_test.py
```

**Comment by professor-ben** [comment]
Hm. I would recommend pairing with a technical coach on this one and circling back if you can't figure something out. The file structure looks OK here and I haven't seen this issue with other students who have submitted, so there's probably something small that's off in your configuration.

**Comment by Jiyu13** [comment]
Thanks. I did try paring with TCs but they said they were not familiar with Codegrade and recommeded me ask the instructors for help and i did but the problem's still there, so I'm just wondering if there would be solution for this problem because it happens to me quite often.

**Comment by lslayman** [comment]
Hi! I'm also experiencing this error!

**Comment by angski11422** [comment]
I also had this issue. All pytests passing in VSC but failed in code grade.

**Comment by morgvanny** [comment]
based on some testing, it appears that multiple tests have the same docstring, so pytest may be treating them as the same tests when totaling the number passing, yet it still counts all of them to compute the total number of tests. it seems if we change the docstrings to give each test a unique description, it counts the percentage complete accurately, so that's something we should fix on our end

**Comment by linda-seiter** [comment]
Hmm,  the issue with the tables not being found was due to a missing per student setup script in the Codegrade assignment. 

cd server && python3 -m flask db upgrade && python3 seed.py


Once that is added to the Codegrade assignment, the tests passed in the course I looked at.  Can you check if that setup script was in your assignment?

Also, there was an error in the solution models.py with Bakery and BakedGoods having a unique constraint  for the name column but the metadata naming convention was not set up for unique constraints.  The solution is being updated to fix that.

**Comment by lslayman** [comment]
I ran "cd server && python3 -m flask db upgrade && python3 seed.py" as suggested and codegrade still reflects my tests as failing. I have experienced this issue with every lab in this phase, as has several of my peers.

**Comment by linda-seiter** [comment]
@Islayman, I cloned your repo and submitted it to Codegrade and it passed the tests.  Maybe there is an issue with either your Canvas or github account.  Can we setup a time to do a zoom so you can step me through how Canvas and/or Codegrade is having you submit the assignment?  You can contact me at linda.seiter@flatironschool.com

**Comment by linda-seiter** [comment]
codegrade updated
