### ISSUE TITLE
Re-wording instructions to actually run flask db init

### ISSUE THREAD

**Issue by sheenasany** [learn-co-curriculum/python-p4-building-get-api-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208452?module_item_id=480485

### Concern

Following the instructions, it tells you that flask db init has already been run for you, but if I try to run to create a migration after I've built out the models, I get an error that the file is not found. If I try to run flask db init, it tells me that the migrations as already been created and it's not empty. 

My solution for this was to move the migrations folder that was created without a versions folder outside of the server directory and ran the flask db init command once more and it ran, along with the create migrations command which also ran seamlessly. 

We need to change to re-wording so that students SHOULD be running the flask db init command before running the migrations to create the version folder. 

### Additional Context

![image](https://user-images.githubusercontent.com/105241920/228707886-19309de1-d51f-41e3-a63f-10e3dc388740.png)

![image](https://user-images.githubusercontent.com/105241920/228707987-bdc87407-5e6e-4f37-8f98-4aae6993b7a7.png)

![image](https://user-images.githubusercontent.com/105241920/228708091-ef42c9a6-9f85-4f86-ac83-5ba6bb6a6453.png)

**Comment by sbasken** [comment]
I had exactly the same issue with this. Nothing worked and I deleted the migrations directory, ran 'flask db init' to create a new one and it worked fine so there seems to be an issue with the existing migrations directory in this repo.

**Comment by afromatt6288** [comment]
Same happened here. I am glad someone else led the way, or I would have been stuck. Please update it soon.

**Comment by professor-ben** [comment]
Thanks so much to everyone for reporting this issue! I pushed a couple of changes that I believe will address the problems you saw here. If you don't mind going back through the lab with the updated instructions, it would be very helpful to us to make sure we know how to address any similar issues going forward.

Thanks again,
Ben
