### ISSUE TITLE
flask db init

### ISSUE THREAD

**Issue by vargasmichael** [learn-co-curriculum/python-p4-building-get-api-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236243?module_item_id=554229

### Concern

The instructions say that <flask db init> has already been run and you can go ahead and run <flask db revision --autogenerate -m'<your message>'>
and then <flask db upgrade>. However I ran into a ton of errors and then I went back and ran <flask db init> along with the other commands and it worked. It appears that you still need to run <flask db init> even though the instructions say that it has already been run.

**Comment by professor-ben** [comment]
Hi Michael,

Thanks so much for reporting this issue! I pushed a couple of changes that I believe will address the problems you saw here. If you don't mind going back through the lab with the updated instructions to make sure it's working now, it would be very helpful to us.

Thanks again,
Ben
