### ISSUE TITLE
this lab is broken with the source code 

### ISSUE THREAD

**Issue by bbissette3** [learn-co-curriculum/python-p4-building-get-api-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/6275/assignments/237677?module_item_id=558420

### Concern

following the instructions  just does not work. there is an issue with the migrations that come with the fork/clone.

### Additional Context

doing nothing but following the instructions will break the lab no matter what you do. Confirmed multiple different ways with my instructors.

### Suggested Changes

the only thing you can do to get this to work is delete the entire migrations folder and run flask db init yourself.

**Comment by professor-ben** [comment]
Hi Brian,

I just went through this lab on my work computer and didn't have any issues. I deleted and regenerated the starter migrations and pushed them up- if you get the chance, could you try recloning the repo and running `flask db upgrade head` in the `server/` directory?

Thanks,
Ben

**Comment by professor-ben** [comment]
Hi again Brian,

I had a couple coworkers go through this lab with the new updates and they're saying it's working fine- if you want to check in and let me know how it's working for you, we can reopen if needed in the future.

Thanks,
Ben
